services:
  # 1. API y Dashboard Web (Salud Predictiva - FastAPI)
  api:
    build: .
    container_name: salud_predictiva_api
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=app-db
      - DB_NAME=uci_telemetria
      - DB_USER=admin
      - DB_PASS=adminpassword
      - HAPI_FHIR_URL=http://hapi-fhir:8080/fhir
      - PORT=8000
    depends_on:
      - app-db
    restart: unless-stopped

  # 2. Base de datos PostgreSQL Nativa (Modelo Relacional Telemetría UCI)
  app-db:
    image: postgres:15-alpine
    container_name: uci_app_db
    environment:
      POSTGRES_DB: uci_telemetria
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
    ports:
      - "5433:5432"
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
      - app_db_data:/var/lib/postgresql/data
    restart: unless-stopped

  # 3. Visor de Base de Datos Web (Adminer)
  adminer:
    image: adminer:latest
    container_name: uci_adminer
    ports:
      - "8081:8080"
    depends_on:
      - app-db
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

  # 4. Base de datos para HAPI FHIR
  fhir-db:
    image: postgres:15-alpine
    container_name: hapi_fhir_db
    environment:
      POSTGRES_DB: hapifhir
      POSTGRES_USER: fhiruser
      POSTGRES_PASSWORD: fhirpassword
    ports:
      - "5432:5432"
    volumes:
      - fhir_db_data:/var/lib/postgresql/data
    restart: unless-stopped

  # 5. Servidor HAPI FHIR R4
  hapi-fhir:
    image: hapiproject/hapi:latest
    container_name: hapi_fhir_server
    ports:
      - "8080:8080"
    environment:
      hapi.fhir.fhir_version: R4
      spring.datasource.url: jdbc:postgresql://fhir-db:5432/hapifhir
      spring.datasource.username: fhiruser
      spring.datasource.password: fhirpassword
      spring.datasource.driverClassName: org.postgresql.Driver
      spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    depends_on:
      - fhir-db
    restart: unless-stopped

volumes:
  app_db_data:
  fhir_db_data: